name: absensi_bkr
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.0
  dropdown_search: ^6.0.1
  easy_date_timeline: ^2.0.6
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  http: ^1.4.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  qrcode_reader_web: ^1.1.1
  scanning_effect: ^1.0.7
  shared_preferences: ^2.3.5
  skeletonizer: ^1.4.3
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/badge/
    - asset/font/
    - asset/image/
    - asset/logo/
    - asset/lottiefiles/

  fonts:
    - family: NeatChalk
      fonts:
        - asset: asset/font/neat-chalk.ttf
